# Partie 2 : eksctl create cluster -f eks/cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: io-eks-2
  region: eu-west-3
managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
