aws_region             = "eu-west-3"
vpc_name               = "jenkins-vpc"
vpc_cidr               = "10.0.0.0/16"
public_subnets         = ["10.0.1.0/24"]
instance_type          = "t3.large"
jenkins_ec2_instance   = "Jenkins-Build-Server"
jenkins_security_group = "jenkins-sg"
key_name               = "io-key"
my_ip_cidr             = "203.0.113.10/32" # ← REMPLACE par ton IP
