dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // jcenter() est fermé : mavenCentral() suffit
    }
}
rootProject.name = "GradlePlayground"
include ':app'
include ':first'
include ':second'
