# /etc/prometheus/prometheus.yml du serveur "monitoring" (projet 30)
global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx] # module de blackbox.yml : attend un code 2xx
    static_configs:
      - targets:
          - http://blog.mon-domaine.fr # ← ton domaine ou le DNS du load balancer
          - https://www.google.com # cible témoin
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target # l'URL à sonder devient ?target=
      - source_labels: [__param_target]
        target_label: instance # label affiché dans Grafana
      - target_label: __address__
        replacement: localhost:9115 # Prometheus interroge en réalité le Blackbox Exporter
