# Étape 6 : Service LoadBalancer (AWS crée un load balancer — à supprimer AVANT le cluster)
apiVersion: v1
kind: Service
metadata:
  name: mygame-svc
spec:
  selector:
    app: 2048-ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
